[package]
name = "repl"
version = "0.1.0"
edition = "2024"


[[bin]]
name = "repl"
path = "src/main.rs"

[dependencies]
sqlite = { version = "0.36.1", default-features = false }
rustyline = "14.0"

[workspace]
